#version 450
#extension GL_GOOGLE_include_directive : require
#include "common.glsl"
#include "lattice.glsl"
#include "triangle_cells.glsl"
layout(local_size_x = 256) in;
layout(set = 0, binding = 5, std430) writeonly buffer CurrentRoots {
    Root currentRoots[];
};
layout(set = 0, binding = 6, std430) readonly buffer PreviousRoots {
    Root previousRoots[];
};
void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= uint(params.gridExtent.x * params.gridExtent.y * params.gridExtent.z))
        return;
    int old = previousRoots[id].owner == 0u ? -1 : int(previousRoots[id].lod);
    float d = distance((vec3(regionAt(id)) + .5) * regionSize(), frame.cameraTime.xyz);
    currentRoots[id].owner = id + 1u;
    currentRoots[id].lod = uint(distanceLod(d, old));
}
